#!/bin/bash

# to install:
# - yum install gnuplot
#
# helpful websites
# - http://www.gnuplot.info/
# - http://www.gnuplot.info/docs_5.4/Gnuplot_5.4.pdf
# - https://alvinalexander.com/technology/gnuplot-charts-graphs-examples/

file=$1
if [ "$file" = "" ]; then
  echo "ERROR filename arg expected"
  exit 1
fi

gnuplot -p -e "plot '$file' with linespoints"
